version: "3.8"
services:
  mysql:
      image: mysql:5.7.24
      container_name: mysql
      networks:
      - nodeservice-net
      env_file: .env
      environment:
        MYSQL_DATABASE: nodeservice
        MYSQL_USER: root
        MYSQL_PASSWORD: root123
      ports:
        - "3307:3306"
      volumes:
        - ${PWD}/mysql:/var/lib/mysql
  app:
    build: .
    container_name: nodeservice
    networks:
      - nodeservice-net
    #restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - /home/node/app
networks:
  nodeservice-net:
    driver: bridge